=== usnistgov/PETs_ppfl/schemas/ClientReportSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Client Outputs",
    "description": "Schema defining the output of the data contents",
    "type": "object",
    "properties":
        {
            "created on":
                {
                    "description": "The timestamp of when the report was created",
                    "type": "string"
                },
            "model id":
                {
                    "description": "The id of the model trained",
                    "type": "integer"
                },
            "round number":
                {
                    "description": "The round of training",
                    "type": "integer"
                },
            "partitions file":
                {
                    "description": "The file used to partition the data for training",
                    "type": "string"
                },
            "train accuracy":
                {
                    "description": "Training accuracy for this client and round",
                    "type": "number"
                },
            "test accuracy":
                {
                    "description": "Test accuracy for this client and round",
                    "type": "number"
                },
            "train mean squared error":
                {
                    "description": "Train MSE for this client and round",
                    "type": "number"
                },
            "test mean squared error":
                {
                    "description": "Test MSE for this client and round",
                    "type": "number"
                },
            "train loss":
                {
                    "description": "Train loss for this client and round",
                    "type": "number"
                },
            "test loss":
                {
                    "description": "Test loss for this client and round",
                    "type": "number"
                },
            "train indices":
                {
                    "description": "Indices used for training",
                    "type": "array",
                    "items": 
                        {
                            "type": "integer"
                        }
                },
            "test indices":
                {
                    "description": "Indices used for testing",
                    "type": "array",
                    "items": 
                        {
                            "type": "integer"
                        }
                },
            "train accuracy per epoch":
                {
                    "description": "Accuracy over epochs for training",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "test accuracy per epoch":
                {
                    "description": "Accuracy over epochs for testing",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "train mse per epoch":
                {
                    "description": "MSE over epochs for training",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "test mse per epoch":
                {
                    "description": "MSE over epochs for testing",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "losses per epoch":
                {
                    "description": "Loss values for each epoch in this client round",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "epsilon per epoch":
                {
                    "description": "The epsilon values for each epoch in this client round",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "train predictions":
                {
                    "description": "The predicted values for the training set",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "test predictions":
                {
                    "description": "The predicted values for the test set",
                    "type": "array",
                    "items": 
                        {
                            "type": "number"
                        }
                },
            "hyperparameters": 
                {
                    "description": "The hyperparameters the client used during its training process",
                    "type": "object",
                    "properties": 
                        {
                            "learning rate":
                                {
                                    "description": "Sets the model's learning rate. This defines how much a model changes at each iteration",
                                    "type": "number"
                                },
                            "weight decay":
                                {
                                    "description": "Sets the model's weight decay. This is a regularization method that penalizes high weights",
                                    "type": "number"
                                },
                            "batch divisor":
                                {
                                    "description": "The divisor to determine the number of batches (num_batches = dataset_size/batch_divisor)",
                                    "type": "integer"
                                },
                            "epochs":
                                {
                                    "description": "The number of model training epochs. An epoch is one full pass through a training dataset",
                                    "type": "integer"
                                },
                            "seed":
                                {
                                    "description": "The seed used to randomize training/testing",
                                    "type": "integer"
                                },
                            "test fraction":
                                {
                                    "description": "The fraction of the data set to set aside for testing",
                                    "type": "number"
                                },
                            "accuracy tolerance":
                                {
                                    "description": "Error tolerance to declare prediction as correct",
                                    "type": "number"
                                },
                            "optimizer":
                                {
                                    "description": "The optimizer is responsible for adjusting model parameters based on the value of the loss function",
                                    "type": "string"
                                },
                            "epsilon":
                                {
                                    "description": "Determines the amount of privacy added to the data. ",
                                    "type": "number"
                                },
                            "delta":
                                {
                                    "description": "Measures the chance of a data breach. It defines the probability of the noise not adding sufficient privacy",
                                    "type": "number"
                                },
                            "max grad norm": 
                                {
                                    "description": "Clips the gradients to be under this maximum before adding noise",
                                    "type": "number"
                                }
                        }
                }
        }
}

=== usnistgov/PETs_ppfl/sampleReports/SampleClientReport.json
{
    "created on": "2026-05-05 14:37:18.166190",
    "model id": 0,
    "round number": 0,
    "partitions file": "none",
    "train accuracy": 0.02127659574468085,
    "test accuracy": 0.010526315789473684,
    "train mean squared error": 1.6443989755111332,
    "test mean squared error": 1.702289968583251,
    "train loss": 144.8086700439453,
    "test loss": 120.62084636688232,
    "train indices": [
        185,
        340,
        412,
        144,
        50,
        423,
        427,
        347,
        371,
        264,
        441,
        46,
        132,
        298,
        351,
        464,
        348,
        345,
        352,
        120,
        140,
        101,
        456,
        421,
        174,
        330,
        460,
        183,
        64,
        154,
        413,
        289,
        321,
        261,
        324,
        150,
        326,
        358,
        8,
        447,
        133,
        410,
        388,
        219,
        176,
        82,
        86,
        319,
        151,
        363,
        229,
        382,
        249,
        337,
        147,
        335,
        299,
        411,
        342,
        184,
        402,
        24,
        364,
        244,
        252,
        362,
        334,
        68,
        271,
        56,
        433,
        19,
        162,
        178,
        179,
        336,
        228,
        60,
        384,
        73,
        280,
        3,
        422,
        434,
        379,
        394,
        230,
        193,
        202,
        118,
        453,
        126,
        293,
        47,
        439,
        127,
        146,
        210,
        27,
        361,
        62,
        393,
        466,
        307,
        328,
        172,
        370,
        322,
        143,
        268,
        374,
        38,
        389,
        29,
        89,
        254,
        98,
        119,
        148,
        196,
        359,
        302,
        134,
        226,
        12,
        242,
        67,
        108,
        84,
        350,
        201,
        385,
        306,
        30,
        7,
        285,
        459,
        258,
        25,
        92,
        442,
        448,
        91,
        241,
        451,
        283,
        233,
        377,
        40,
        381,
        156,
        443,
        181,
        455,
        104,
        75,
        250,
        444,
        180,
        259,
        135,
        165,
        331,
        438,
        149,
        70,
        255,
        288,
        368,
        54,
        355,
        169,
        291,
        215,
        419,
        425,
        158,
        470,
        95,
        468,
        315,
        186,
        263,
        257,
        318,
        429,
        418,
        292,
        88,
        356,
        436,
        248,
        214,
        37,
        367,
        270,
        344,
        276,
        161,
        216,
        207,
        407,
        173,
        112,
        18,
        153,
        11,
        469,
        205,
        310,
        406,
        66,
        9,
        375,
        59,
        417,
        404,
        4,
        94,
        48,
        93,
        251,
        327,
        32,
        155,
        128,
        121,
        227,
        130,
        81,
        308,
        311,
        52,
        391,
        28,
        416,
        209,
        106,
        401,
        463,
        21,
        218,
        414,
        266,
        432,
        341,
        39,
        360,
        188,
        13,
        189,
        357,
        369,
        220,
        5,
        85,
        378,
        373,
        376,
        332,
        278,
        78,
        435,
        114,
        170,
        339,
        123,
        301,
        103,
        90,
        199,
        274,
        397,
        206,
        87,
        221,
        142,
        111,
        329,
        383,
        277,
        349,
        430,
        187,
        65,
        446,
        99,
        71,
        424,
        69,
        387,
        125,
        177,
        224,
        454,
        117,
        74,
        372,
        10,
        116,
        405,
        157,
        63,
        223,
        1,
        42,
        122,
        17,
        167,
        297,
        309,
        76,
        313,
        296,
        208,
        325,
        31,
        129,
        415,
        105,
        290,
        267,
        398,
        212,
        43,
        440,
        160,
        317,
        57,
        279,
        23,
        420,
        272,
        15,
        316,
        109,
        137,
        190,
        287,
        16,
        300,
        240,
        110,
        431,
        195,
        34,
        286,
        314,
        35,
        333,
        182,
        49,
        6,
        102,
        175,
        139,
        452,
        41,
        366,
        22,
        275,
        163,
        320,
        303,
        113,
        237,
        396,
        437,
        14,
        141,
        194,
        36,
        97,
        449,
        461,
        136
    ],
    "test indices": [
        428,
        234,
        295,
        253,
        45,
        145,
        305,
        107,
        0,
        61,
        450,
        200,
        166,
        204,
        198,
        386,
        222,
        294,
        457,
        138,
        465,
        77,
        236,
        217,
        243,
        409,
        171,
        164,
        354,
        115,
        445,
        304,
        152,
        197,
        231,
        33,
        467,
        260,
        282,
        191,
        100,
        51,
        20,
        159,
        53,
        80,
        235,
        395,
        265,
        392,
        83,
        380,
        124,
        203,
        426,
        273,
        338,
        408,
        55,
        269,
        245,
        238,
        400,
        284,
        247,
        213,
        79,
        390,
        312,
        211,
        281,
        131,
        403,
        225,
        44,
        232,
        168,
        343,
        246,
        26,
        256,
        2,
        192,
        458,
        365,
        323,
        58,
        72,
        462,
        353,
        346,
        399,
        239,
        262,
        96
    ],
    "train accuracy per epoch": [
        0.02925531914893617
    ],
    "test accuracy per epoch": [
        0.010526315789473684
    ],
    "train mse per epoch": [
        3.035118691464688
    ],
    "test mse per epoch": [
        1.7022899527298776
    ],
    "losses per epoch": [
        0.9972543342243507
    ],
    "epsilon per epoch": [
        2476.591583251953
    ],
    "train predictions": [
        1.3697792291641235,
        1.3778330087661743,
        1.1389683485031128,
        1.3958735466003418,
        1.259084939956665,
        1.3683805465698242,
        1.1912509202957153,
        1.4103240966796875,
        1.4172979593276978,
        1.3829593658447266,
        1.289253830909729,
        1.3630592823028564,
        1.3635615110397339,
        1.4293080568313599,
        1.290304183959961,
        1.3940155506134033,
        1.3173904418945312,
        1.283046841621399,
        1.3429186344146729,
        1.3593523502349854,
        1.3444980382919312,
        1.395972728729248,
        1.3551722764968872,
        1.3028581142425537,
        1.3286672830581665,
        1.2392271757125854,
        1.3884079456329346,
        1.1407305002212524,
        1.4096282720565796,
        1.2147835493087769,
        1.1382969617843628,
        1.4034976959228516,
        1.3458448648452759,
        1.062523603439331,
        1.37980055809021,
        1.3959795236587524,
        1.2727402448654175,
        1.3351958990097046,
        1.335971474647522,
        1.3479892015457153,
        0.9950622916221619,
        1.3558920621871948,
        1.415916919708252,
        1.0827207565307617,
        1.392121434211731,
        1.262679934501648,
        1.3771772384643555,
        1.1968470811843872,
        1.1085444688796997,
        1.1263880729675293,
        1.251936435699463,
        1.3550785779953003,
        1.3676825761795044,
        1.2023605108261108,
        1.3426239490509033,
        1.2765631675720215,
        1.407353401184082,
        1.3961588144302368,
        1.3029810190200806,
        1.359176754951477,
        1.3572478294372559,
        1.2416845560073853,
        1.2645235061645508,
        1.1549837589263916,
        1.334802269935608,
        1.4046283960342407,
        1.2935837507247925,
        1.3001152276992798,
        1.3627492189407349,
        1.3841748237609863,
        1.3907376527786255,
        1.3465594053268433,
        1.3121693134307861,
        1.3151378631591797,
        1.4060914516448975,
        1.3616470098495483,
        1.4026668071746826,
        1.3098889589309692,
        1.229169487953186,
        1.407912015914917,
        1.3707506656646729,
        1.0887287855148315,
        1.4099820852279663,
        1.321511149406433,
        1.2674013376235962,
        1.414318561553955,
        1.3957024812698364,
        1.3837027549743652,
        1.364701509475708,
        1.17637300491333,
        1.3443330526351929,
        1.1853523254394531,
        1.3930449485778809,
        1.1902180910110474,
        1.2482551336288452,
        1.3601768016815186,
        1.4043998718261719,
        1.3386093378067017,
        1.3367395401000977,
        1.3983442783355713,
        1.3564354181289673,
        1.309195876121521,
        1.3626337051391602,
        1.417047142982483,
        1.175300121307373,
        1.406169056892395,
        1.3737752437591553,
        1.359329104423523,
        1.3594143390655518,
        1.1830098628997803,
        1.1459143161773682,
        1.2497406005859375,
        1.1557426452636719,
